pub mod reverse_array;
pub mod count_positive_sum_negative;
pub mod paperwork;
pub mod maps;
pub mod make_negative;
pub mod greet_string;
pub mod messi_goals;
pub mod remove_char;
pub mod square_array;